minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
# DCloud 固定的历史 Vite 插件缺少部分早期版本具有的来源证明
trustPolicyIgnoreAfter: 525600
autoInstallPeers: true
strictPeerDependencies: false
shamefullyHoist: true
shellEmulator: true

packages:
  - tools/testing

overrides:
  giget@1.2.5>tar: 7.5.22

patchedDependencies:
  '@uni-helper/unh@0.3.2': patches/@uni-helper__unh@0.3.2.patch
  '@uni-helper/vite-plugin-uni-pages@0.5.0': patches/@uni-helper__vite-plugin-uni-pages@0.5.0.patch
  '@unocss/vite@66.10.1': patches/@unocss__vite@66.10.1.patch
  devframe@0.9.18: patches/devframe@0.9.18.patch

allowBuilds:
  '@parcel/watcher': true
  '@uni-helper/unocss-preset-uni': true
  bufferutil: true
  core-js: true
  core-js-pure: false
  esbuild: true
  minidev: true
  vue-demi: true
