/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogos: typeof import('./components/AppLogos.vue')['default']
    InputEntry: typeof import('./components/InputEntry.vue')['default']
    PageWraper: typeof import('./components/PageWraper/index.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup/index.vue')['default']
    WdBadge: typeof import('wot-design-uni/components/wd-badge/wd-badge.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdCell: typeof import('wot-design-uni/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('wot-design-uni/components/wd-cell-group/wd-cell-group.vue')['default']
    WdConfigProvider: typeof import('wot-design-uni/components/wd-config-provider/wd-config-provider.vue')['default']
    WdDivider: typeof import('wot-design-uni/components/wd-divider/wd-divider.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdImg: typeof import('wot-design-uni/components/wd-img/wd-img.vue')['default']
    WdInput: typeof import('wot-design-uni/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['default']
    WdLoadmore: typeof import('wot-design-uni/components/wd-loadmore/wd-loadmore.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdNotify: typeof import('wot-design-uni/components/wd-notify/wd-notify.vue')['default']
    WdOverlay: typeof import('wot-design-uni/components/wd-overlay/wd-overlay.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdResize: typeof import('wot-design-uni/components/wd-resize/wd-resize.vue')['default']
    WdSearch: typeof import('wot-design-uni/components/wd-search/wd-search.vue')['default']
    WdSticky: typeof import('wot-design-uni/components/wd-sticky/wd-sticky.vue')['default']
    WdStickyBox: typeof import('wot-design-uni/components/wd-sticky-box/wd-sticky-box.vue')['default']
    WdSwiper: typeof import('wot-design-uni/components/wd-swiper/wd-swiper.vue')['default']
    WdSwiperNav: typeof import('wot-design-uni/components/wd-swiper-nav/wd-swiper-nav.vue')['default']
    WdTab: typeof import('wot-design-uni/components/wd-tab/wd-tab.vue')['default']
    WdTabbar: typeof import('wot-design-uni/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('wot-design-uni/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
    WdTabs: typeof import('wot-design-uni/components/wd-tabs/wd-tabs.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
    WdTransition: typeof import('wot-design-uni/components/wd-transition/wd-transition.vue')['default']
  }
}
