/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppPageWrapper: typeof import('./../components/App/PageWrapper.vue')['default']
    Navbar: typeof import('./../components/Navbar/index.vue')['default']
    StatusBar: typeof import('./../components/StatusBar/index.vue')['default']
    Tabbar: typeof import('./../components/Tabbar/index.vue')['default']
  }
}
