/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/tests/refs" |
  "/packages/demo/pages/hi" |
  "/packages/demo/pages/index" |
  "/packages/demo/pages/paging-basic" |
  "/packages/demo/pages/paging-filter" |
  "/packages/demo/pages/paging-states" |
  "/packages/demo/pages/request" |
  "/packages/demo/pages/wot" |
  "/packages/journal/pages/appearance" |
  "/packages/journal/pages/info" |
  "/packages/journal/pages/note-editor" |
  "/packages/journal/pages/saved" |
  "/packages/journal/pages/story";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index" | "/pages/notes" | "/pages/about"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
