name: deploy `@uniapp-template/components`

on:
  workflow_dispatch: # 手动触发
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Node.js 版本
          cache: 'pnpm'  # 缓存 pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm run build:comp

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/components/dist/build/h5  # 构建输出目录
          publish_branch: gh-pages/components  # 指定分支名称